name: 自动生成Gather.m3u

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'  # 北京 06:00
    - cron: '0 9 * * *'   # 北京 17:00
  push:
    paths:
      - 'scripts/merge_ff.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python scripts/merge_ff.py

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git add Gather.m3u
          git commit -m "Update Gather.m3u" || exit 0
          git push
