name: 自动生成 Gather.m3u

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'
    - cron: '0 22 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - run: pip install requests

    - run: python scripts/merge_ff.py

    - name: 提交
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add Gather.m3u
        git commit -m "update" || echo "no change"
        git push
